config/routes.rb
Rails.application.routes.draw do
  get 'about/top'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'about#top'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update ,:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :name,    length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }
  # validates :profile_image, presence: true

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = @book.user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.all
    @book_new = Book.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      flash[:notice] = "have updated book successfully."
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      flash[:notice] = "You have updated user successfully."
    else
      redirect_to user_path(current_user.id)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to user_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @user = current_user
    @books = @user.books
    @book = Book.new
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:introduction, :name, :profile_image)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/top.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <h1 class="px-3 mx-auto">
                Welcome to
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>
                !
            </h1>
        </div>
    </div>
</main>
        

app/views/books/_list.html.erb
<p id="notice"><%= flash[:notice] %></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, size: "100x100", format: 'png', fallback: "No_image.png", class: 'attachment user profile_image' %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= book.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
        </div>


        <h2 class="mt-3">New book</h2>

        <%= form_with model:book_new, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Book</h2>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>error
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, autofocus: true, id:"inputTitle", class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, autofocus: true, id:"inputBody", class: 'form-control book_body' %>
          </div>
          <div>
          <%= f.submit "Update Book", class: 'btn btn-success' %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book), class:"link-text" %>
          |
        <%= link_to "Back", books_path, class:"link-text" %>
      </div>
    </div>
  </div>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <table>
          <%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'png', fallback: "No_image.png", class: 'attachment user profile_image' %>
          <tbody class="table">
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
        </div>

        <h2>New book</h2>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>error
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to book.user do %>
                  <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'png', fallback: "No_image.png" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
        <% end %>

        </table>
      </main>

      </div>
    </div>
  </div>

app/views/books/show.html.erb
<main>
  <%= render 'books/list', user: @user, book: @book, book_new: @book_new %>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <th>
            <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'png', fallback: "No_image.png", class: 'attachment user profile_image' %>
              <br>
              <%= @user.name %>
            <% end %>
          </th>
          <th>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success edit_book_1112' %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-sm btn-danger destroy_book_1112' %></td>
            
            <% end %>
          </th>
        </tr>
      </tbody>
    </table>
  </div>
</main>

app/views/homes/top.html.erb
<main>
    <p id="notice"><%= flash[:notice] %></p>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                <h1>
                    welcome to
                    <i class="fas fa-book"></i>
                    <strong>Bookers</strong>
                    !!
                </h1>
                <p>
                    In
                    <i class="fas fa-book"></i>
                    <strong>Bookers</strong>
                    ,
                </p>

                <p>you can share and exchange your opinions , inpressions , and emotions</p>
                <p>about various books!</p>

                <% if user_signed_in? %>
                    <div class="btn-wrapper col-10 mx-auto">
                        <div class="row">
                            <%= link_to "Log in", user_path(current_user.id), class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
                        </div>
                        <div class="row">
                            <%= link_to "Sign Up", user_path(current_user.id), class: 'btn btn-success btn-sm btn-block sign_up' %>
                        </div>
                    </div>
                <% else %>
                    <div class="btn-wrapper col-10 mx-auto">
                        <div class="row">
                            <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
                        </div>
                        <div class="row">
                            <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <% if user_signed_in? %>
            <span>
              <%= link_to "Bookers",root_path, class: 'navbar-brand' %>
            </span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Users", user_registration_path, class: 'fas fa-users nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
                </li >
                <li>
                  <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
                </li>
              </ul>
            </div>
          <% else %>
            <span>
              <%= link_to "Bookers",root_path, class: 'navbar-brand' %>
            </span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to " Home",root_path, class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " About",home_about_path, class: 'fas fa-link nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, size: "100x100", format: 'png', fallback: "No_image.png", class: 'attachment user profile_image' %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
        </div>


        <h2 class="mt-3">New book</h2>

        <%= form_with model:book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>error
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: 'form-control name' %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "ファイルを選択", class: 'form-control-file user_image' %>
          </div>  
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, autofocus: true, id:"inputinputIntroduction", class: 'form-control introduction' %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User",class: 'btn btn-secondary' %>
          </div>  
        <% end %>
      </div>
    </div>
  </div>
</main>
        
            

app/views/users/index.html.erb
<main>
  <%= render 'users/list', user: @user, book: @book %>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <% @users.each do |user| %>
      <tbody>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, size: "40x40", format: 'png', fallback: "No_image.png" %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      </tbody>
    <% end %>
    </table>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <%= render 'users/list', user: @user, book: @book %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, size: "50x50", format: 'png', fallback: "No_image.png" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
        <% end %>
        </table>
      </div>
    </div>
  </div>
</main>